sudo: false
language: python
python:
  - "2.7"
install:
    - pip install coveralls
    - pip install -r requirements.txt
    - pip install -r ckanext/versioned_datastore/tests/requirements.txt
script:
    - pytest --cov=ckanext.versioned_datastore
after_success: coveralls
